name: "terraform"

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform:
    uses: schubergphilis/mcaf-github-workflows/.github/workflows/terraform-validation.yml@main
